spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mudspoon_front
    username: "root"
    password: "1234"
  jpa:
    hibernate:
      ddl-auto : update
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  generate-ddl : true
  show-sql: true
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mudspoon


server:
  servlet:
    context-path: /api
logging:
  level:
    org:
      hibernate:
        type: trace
        SQL: info



