spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://dbname:3306/mudspoon_front?characterEncoding=UTF-8&serverTimezone=UTC
    username: "root"
    password: "1234"
  jpa:
    hibernate:
      ddl-auto : update
      show-sql: false
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  generate-ddl : true
  show-sql: false
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      host: mongodbname
      port: 27017
      database: mudspoon


logging:
  level:
    org:
      hibernate:
        type: trace
        SQL: info



