spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://rdb1.cajkxrgtuzp2.us-east-1.rds.amazonaws.com:3306/mudspoon_front?useUnicode=true
    username: "root"
    password: "1234"
  jpa:
    hibernate:
      ddl-auto : update
      show-sql: false
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  generate-ddl : true
  show-sql: false
  output:
    ansi:
      enabled: always
#  data:
#    mongodb:
#      host: mongodbname
#      port: 27017
#      database: mudspoon


logging:
  level:
    org:
      hibernate:
        type: trace
        SQL: info



