server:
  servlet:
    context-path: /api


spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://rdb1.cajkxrgtuzp2.us-east-1.rds.amazonaws.com:3306/mudspoon_front?useUnicode=true
    username: "root"
    password: "luminate1024*^#"
  jpa:
    hibernate:
      ddl-auto : update
      show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  generate-ddl : true
  show-sql: true
  output:
    ansi:
      enabled: always
  devtools:
    remote:
      secret: mysecret
#  data:
#    mongodb:
#      host: mongodbname
#      port: 27017
#      database: mudspoon

logging:
  level:
    org:
      hibernate:
        type: trace
        SQL: info
